# Generated by Django 6.0.2 on 2026-03-01 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tti', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='admission_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
