# Generated by Django 6.0.2 on 2026-03-01 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tti', '0003_course_remove_unit_lecturer_name_alter_unit_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('certificate', 'Certificate'), ('diploma', 'Diploma')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tti.course'),
        ),
        migrations.DeleteModel(
            name='Timetable',
        ),
    ]
