# Generated by Django 6.0.2 on 2026-03-01 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tti', '0004_course_level_alter_customuser_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tti.course'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tti.course'),
        ),
    ]
