# Generated by Django 6.0.2 on 2026-03-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tti', '0007_alter_course_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='course',
        ),
        migrations.AddField(
            model_name='unit',
            name='course',
            field=models.ManyToManyField(blank=True, related_name='units', to='tti.course', verbose_name='Courses this unit belongs to'),
        ),
    ]
