# Generated by Django 6.0.2 on 2026-03-01 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tti', '0008_remove_unit_course_unit_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='year_of_study',
        ),
    ]
