# Generated by Django 6.0.2 on 2026-03-01 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tti', '0009_remove_unit_semester_remove_unit_year_of_study'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='department',
        ),
    ]
