# Generated by Django 6.0.2 on 2026-03-01 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tti', '0010_remove_customuser_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='year_of_study',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
