# Generated by Django 6.0.2 on 2026-03-01 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tti', '0011_unit_year_of_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructure',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='tti.semester'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tti.course'),
        ),
    ]
