# Generated by Django 6.0.2 on 2026-03-01 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tti', '0012_feestructure_semester_alter_feestructure_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feestructure',
            name='year_of_study',
        ),
    ]
